ARG baseversion=1.0.0
ARG baseimage=base_devenv
FROM ${baseimage}_fpgaext:${baseversion}

ENV DEBIAN_FRONTEND=noninteractive

# Software-only OpenGL setup (for nextpnr and alike)
RUN apt-get update && apt-get install -y libtool-bin autoconf python3-pip libx11-dev libxext-dev x11proto-core-dev x11proto-gl-dev libglew-dev freeglut3-dev bison flex  && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# Build Mesa
WORKDIR /root


RUN apt-get update && apt-get install -y wget pkg-config zlib1g-dev libxcb-xfixes0-dev libxcb-dri2-0-dev glslang-dev glslang-tools libxcb-randr0-dev libxcb-dri3-dev libxcb-present-dev libxshmfence-dev libxrandr-dev meson && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN cd /root/ && wget https://dri.freedesktop.org/libdrm/libdrm-2.4.115.tar.xz && \
    tar -xf libdrm-2.4.115.tar.xz && \
    cd libdrm-2.4.115 && \
    meson builddir && \
    cd builddir && ninja -j16 install \
    && cd /root && rm -rf libdrm-2.4.115*
RUN pip3 install mako
RUN cd /root && wget https://mesa.freedesktop.org/archive/mesa-22.3.2.tar.xz \
    && tar xf mesa-22.3.2.tar.xz && mkdir mesa-22.3.2/build \
    && cd /root/mesa-22.3.2/build \
    && meson .. -Dgallium-drivers=swrast -Dplatforms=x11 -Dgbm=disabled -Degl=disabled -Dosmesa=true -Dglx=xlib -Degl-native-platform=x11 -Dvulkan-drivers=swrast \
    && ninja -j16 install \
    && cd /root && rm -rf mesa-22.3.2*

ENV PATH="/usr/local/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
ENV LIBGL_ALWAYS_SOFTWARE="1" \
    GALLIUM_DRIVER="softpipe"

