ARG baseversion=1.0.0
ARG baseimage=base_devenv
FROM ${baseimage}_fpgaext:${baseversion}

ENV DEBIAN_FRONTEND=noninteractive

# Software-only OpenGL setup (for nextpnr and alike)
RUN apt-get update && apt-get install -y libtool-bin autoconf python3-pip libx11-dev libxext-dev x11proto-core-dev x11proto-gl-dev libglew-dev freeglut3-dev bison flex  && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# Build Mesa
WORKDIR /root
RUN apt-get update && apt-get install -y wget pkg-config zlib1g-dev llvm-dev  && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN cd /root && wget https://mesa.freedesktop.org/archive/mesa-18.2.4.tar.xz \
    && tar xf mesa-18.2.4.tar.xz && mkdir mesa-18.2.4/build \
    && cd /root/mesa-18.2.4/build \
    && ../configure --disable-dri \
               --disable-egl \
               --disable-gbm \
               --with-gallium-drivers=swrast,swr \
               --with-platforms=x11 \
               --prefix=/usr/local \
               --enable-gallium-osmesa \
               --disable-xvmc --disable-vdpau --disable-va \
               --with-swr-archs=avx \
   && make -j 8 && make install && cd /root && rm -rf mesa-18.2.4
ENV PATH="/usr/local/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
ENV LIBGL_ALWAYS_SOFTWARE="1" \
    GALLIUM_DRIVER="softpipe"

